name: My GitHub Action

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 23f1000561@ds.study.iitm.ac.in
        run: echo "Hello, world! This action contains my email address."

      - name: Another step
        run: echo "This is another step after the one with the email."
